//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDataGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestDataGenerator.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó megváltoztatása.
        /// </summary>
        public static string Button_Caption_ChangePassword {
            get {
                return ResourceManager.GetString("Button_Caption_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string Button_Caption_Login {
            get {
                return ResourceManager.GetString("Button_Caption_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijelentkezés.
        /// </summary>
        public static string Button_Caption_Logout {
            get {
                return ResourceManager.GetString("Button_Caption_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisztrálok.
        /// </summary>
        public static string Button_Caption_Register {
            get {
                return ResourceManager.GetString("Button_Caption_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail küldése.
        /// </summary>
        public static string Button_Caption_SendEmail {
            get {
                return ResourceManager.GetString("Button_Caption_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Létrehozás.
        /// </summary>
        public static string Button_Caption_Setup_Create {
            get {
                return ResourceManager.GetString("Button_Caption_Setup_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások mentése.
        /// </summary>
        public static string Button_Caption_Setup_Save {
            get {
                return ResourceManager.GetString("Button_Caption_Setup_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elfelejtett jelszó.
        /// </summary>
        public static string EmailModel_Default_ForgottenPasswordSubject {
            get {
                return ResourceManager.GetString("EmailModel_Default_ForgottenPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Névtelen.
        /// </summary>
        public static string EmailModel_Default_FullName {
            get {
                return ResourceManager.GetString("EmailModel_Default_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres regisztráció.
        /// </summary>
        public static string EmailModel_Default_RegSuccessSubject {
            get {
                return ResourceManager.GetString("EmailModel_Default_RegSuccessSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs tárgy.
        /// </summary>
        public static string EmailModel_Default_Subject {
            get {
                return ResourceManager.GetString("EmailModel_Default_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezzel az e-mail címmel már van regisztrált felhasználó..
        /// </summary>
        public static string Error_EmailAddress_Exists {
            get {
                return ResourceManager.GetString("Error_EmailAddress_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen e-mail cím..
        /// </summary>
        public static string Error_EmailAddress_Invalid {
            get {
                return ResourceManager.GetString("Error_EmailAddress_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a jelszómódosítás során..
        /// </summary>
        public static string Error_ForgottenPassword {
            get {
                return ResourceManager.GetString("Error_ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen felhasználónév vagy jelszó..
        /// </summary>
        public static string Error_Login_InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("Error_Login_InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kötelező mező..
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A szöveg maximális hossza {0} karakter..
        /// </summary>
        public static string Error_StringLength {
            get {
                return ResourceManager.GetString("Error_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küldtünk Önnek egy e-mailt, benne egy, a jelszó módosítását megerősítő linkkel. Az érvényesség lejárati ideje: {0}..
        /// </summary>
        public static string Info_ForgottenPw_VerifyEmailSent {
            get {
                return ResourceManager.GetString("Info_ForgottenPw_VerifyEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissza.
        /// </summary>
        public static string Link_Caption_Back {
            get {
                return ResourceManager.GetString("Link_Caption_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elfelejtett jelszó.
        /// </summary>
        public static string Link_Caption_ForgottenPassword {
            get {
                return ResourceManager.GetString("Link_Caption_ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string Link_Caption_Login {
            get {
                return ResourceManager.GetString("Link_Caption_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijelentkezés.
        /// </summary>
        public static string Link_Caption_Logout {
            get {
                return ResourceManager.GetString("Link_Caption_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisztráció.
        /// </summary>
        public static string Link_Caption_Register {
            get {
                return ResourceManager.GetString("Link_Caption_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új beállítás létrehozása.
        /// </summary>
        public static string Link_Caption_Setup_Create {
            get {
                return ResourceManager.GetString("Link_Caption_Setup_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások szerkesztése.
        /// </summary>
        public static string Link_Caption_Setup_Edit {
            get {
                return ResourceManager.GetString("Link_Caption_Setup_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások megtekintése.
        /// </summary>
        public static string Link_Caption_Setup_List {
            get {
                return ResourceManager.GetString("Link_Caption_Setup_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pl. valaki@mortoff.hu.
        /// </summary>
        public static string Placeholder_Email {
            get {
                return ResourceManager.GetString("Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Név.
        /// </summary>
        public static string Placeholder_Name {
            get {
                return ResourceManager.GetString("Placeholder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszó megváltoztatása sikeres volt..
        /// </summary>
        public static string Success_PasswordChanged {
            get {
                return ResourceManager.GetString("Success_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elfelejtett jelszó.
        /// </summary>
        public static string Title_ForgottenPassword {
            get {
                return ResourceManager.GetString("Title_ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string Title_Login {
            get {
                return ResourceManager.GetString("Title_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijelentkezés.
        /// </summary>
        public static string Title_Logout {
            get {
                return ResourceManager.GetString("Title_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó megváltoztatása.
        /// </summary>
        public static string Title_PasswordChange {
            get {
                return ResourceManager.GetString("Title_PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisztráció.
        /// </summary>
        public static string Title_Register {
            get {
                return ResourceManager.GetString("Title_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások áttekintése.
        /// </summary>
        public static string Title_SetupList {
            get {
                return ResourceManager.GetString("Title_SetupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszónak legalább {0} karakter hosszúnak kell lennie..
        /// </summary>
        public static string Warn_Pw_MinLength {
            get {
                return ResourceManager.GetString("Warn_Pw_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszónak tartalmaznia kell legalább egy számjegyet..
        /// </summary>
        public static string Warn_Pw_MissingDigit {
            get {
                return ResourceManager.GetString("Warn_Pw_MissingDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszónak tartalmaznia kell legalább egy kisbetűt..
        /// </summary>
        public static string Warn_Pw_MissingLowercase {
            get {
                return ResourceManager.GetString("Warn_Pw_MissingLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszónak tartalmaznia kell legalább egy speciális karaktert..
        /// </summary>
        public static string Warn_Pw_MissingSpecial {
            get {
                return ResourceManager.GetString("Warn_Pw_MissingSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszónak tartalmaznia kell legalább egy nagybetűt..
        /// </summary>
        public static string Warn_Pw_MissingUppercase {
            get {
                return ResourceManager.GetString("Warn_Pw_MissingUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jelszónak alfanumerikus karakterrel kell kezdődnie..
        /// </summary>
        public static string Warn_Pw_MustStartWithAlphanumeric {
            get {
                return ResourceManager.GetString("Warn_Pw_MustStartWithAlphanumeric", resourceCulture);
            }
        }
    }
}
